export const categories = [
  {
    title: "Регулярні тури Європою",
    orders: [
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Наталі Василівни і Дмитра Вікторовича Олейників",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
    ],
  },
  {
    title: "Тури під заказні групи",
    orders: [
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
    ],
  },
  {
    title: "Морські тури",
    orders: [
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
      {
        title: "Захоплюючі канікули: Краків + Energylandia",
        daysQuantity: 10,
        tourCost: 1200,
        commission: "10% від вартості туру",
        comment: "Для Н. В.",
      },
    ],
  },
];
