export const countries = [
  { label: "Польша", key: "Польша" },
  { label: "Хорватія", key: "Хорватія" },
  { label: "Франція", key: "Франція" },
  { label: "Туреччина", key: "Туреччина" },
  { label: "Нідерланди", key: "Нідерланди" },
  { label: "Австрія", key: "Австрія" },
  { label: "Румунія", key: "Румунія" },
  { label: "Греція", key: "Греція" },
  { label: "Ватикан", key: "Ватикан" },
  { label: "Німеччина", key: "Німеччина" },
  { label: "Словенія", key: "Словенія" },
  { label: "Швейцарія", key: "Швейцарія" },
  { label: "Чехія", key: "Чехія" },
  { label: "Угорщина", key: "Угорщина" },
  { label: "Італія", key: "Італія" },
];

export const months = [
  { label: "Січень", key: "january" },
  { label: "Лютий", key: "february" },
  { label: "Березень", key: "march" },
  { label: "Квітень", key: "april" },
  { label: "Травень", key: "may" },
  { label: "Червень", key: "june" },
  { label: "Липень", key: "july" },
  { label: "Серпень", key: "august" },
  { label: "Вересень", key: "september" },
  { label: "Жовтень", key: "october" },
  { label: "Листопад", key: "november" },
  { label: "Грудень", key: "december" },
];
