export const countries = [
  { label: "Україна", key: "ukraine" },
  { label: "Польща", key: "poland" },
  { label: "Німеччина", key: "germany" },
  { label: "Франція", key: "france" },
  { label: "Італія", key: "italy" },
  { label: "Іспанія", key: "spain" },
  { label: "Нідерланди", key: "netherlands" },
  { label: "Бельгія", key: "belgium" },
  { label: "Чехія", key: "czechia" },
  { label: "Швейцарія", key: "switzerland" },
  { label: "Австрія", key: "austria" },
  { label: "Швеція", key: "sweden" },
  { label: "Норвегія", key: "norway" },
  { label: "Данія", key: "denmark" },
  { label: "Фінляндія", key: "finland" },
  { label: "Румунія", key: "romania" },
  { label: "Угорщина", key: "hungary" },
  { label: "Греція", key: "greece" },
  { label: "Португалія", key: "portugal" },
  { label: "Ірландія", key: "ireland" },
];

export const months = [
  { label: "Січень", key: "january" },
  { label: "Лютий", key: "february" },
  { label: "Березень", key: "march" },
  { label: "Квітень", key: "april" },
  { label: "Травень", key: "may" },
  { label: "Червень", key: "june" },
  { label: "Липень", key: "july" },
  { label: "Серпень", key: "august" },
  { label: "Вересень", key: "september" },
  { label: "Жовтень", key: "october" },
  { label: "Листопад", key: "november" },
  { label: "Грудень", key: "december" },
];
